### ISSUE TITLE
Hello I am getting this error with MEGENA:  The input PFG has exceeding number of edges.

### ISSUE THREAD

**Issue by ghost** [cran/MEGENA#2]
I am getting this error when I run ddMEGENA() with my ddcor() results.
`Error in serial.PFN(sortedEdge = ijw, Ng = N, maxENum = maxENum) : 
  The input PFG has exceeding number of edges.`

All of my other other data sets (created from identical pipelines) seem to work fine, however I am having this issue?
I don't know what this issue means and why I am having it.

Any suggestions or tips would be much appreciated.

Thank you for you time,
Ashay

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks.

**Comment by ashaypatel** [comment]
I'm sorry I don't follow, where should I ask my question?

Thanks!
